FROM node:22-slim AS build
WORKDIR /app
COPY . .
RUN npm ci && npm run build

FROM nginx:alpine3.22-slim AS production
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
